version: '3'

services:
  local-postgres-compose:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "example"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - demo-project-network
  #rabbit-mq:
  #  image: rabbitmq:3.9-management
  #  restart: always
  #  ports:
  #    - "5672:5672"
  #    - "15672:15672"
  #  networks:
  #    - demo-project-network

networks:
  demo-project-network:
    driver: bridge